In [356]:
import pandas as pd
import numpy as np

In [357]:
df = pd.read_csv('../data/training_data/IPL.csv')

C:\Users\Kartik\AppData\Local\Temp\ipykernel_18696\2496289093.py:1: DtypeWarning: Columns (0: review_batter, 1: team_reviewed, 2: review_decision, 3: umpire, 4: season, 5: superover_winner, 6: result_type, 7: method, 8: event_match_no) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../data/training_data/IPL.csv')

In [358]:
df.shape

(283678, 65)

In [359]:
# data.duplicated().sum()

In [360]:
df.sample(5)

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,...,team_balls,team_wicket,new_batter,power_surge_start,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
11639,153708,336035,2008-05-25,T20,Indian Premier League,1,Kings XI Punjab,Kolkata Knight Riders,7,6,...,48,1,NaN,NaN,18,17,0,"('KC Sangakkara', 'SE Marsh')",NaN,False
177463,40865,1178429,2019-05-04,T20,Indian Premier League,1,Sunrisers Hyderabad,Royal Challengers Bangalore,14,5,...,88,4,NaN,NaN,0,0,0,"('KS Williamson', 'YK Pathan')",NaN,False
75906,217513,548380,2012-05-25,T20,Indian Premier League,1,Chennai Super Kings,Delhi Daredevils,1,5,...,11,0,NaN,NaN,11,5,0,"('M Vijay', 'MEK Hussey')",NaN,False
57368,198975,501266,2011-05-22,T20,Indian Premier League,2,Royal Challengers Bangalore,Chennai Super Kings,17,2,...,104,2,NaN,NaN,12,25,0,"('CH Gayle', 'SS Tiwary')",NaN,False
148337,11739,1082641,2017-05-11,T20,Indian Premier League,2,Mumbai Indians,Kings XI Punjab,2,2,...,14,0,NaN,NaN,8,7,0,"('LMP Simmons', 'PA Patel')",NaN,False

In [361]:
df.columns

Index(['Unnamed: 0', 'match_id', 'date', 'match_type', 'event_name', 'innings',
       'batting_team', 'bowling_team', 'over', 'ball', 'ball_no', 'batter',
       'bat_pos', 'runs_batter', 'balls_faced', 'bowler', 'valid_ball',
       'runs_extras', 'runs_total', 'runs_bowler', 'runs_not_boundary',
       'extra_type', 'non_striker', 'non_striker_pos', 'wicket_kind',
       'player_out', 'fielders', 'runs_target', 'review_batter',
       'team_reviewed', 'review_decision', 'umpire', 'umpires_call',
       'player_of_match', 'match_won_by', 'win_outcome', 'toss_winner',
       'toss_decision', 'venue', 'city', 'day', 'month', 'year', 'season',
       'gender', 'team_type', 'superover_winner', 'result_type', 'method',
       'balls_per_over', 'overs', 'event_match_no', 'stage', 'match_number',
       'team_runs', 'team_balls', 'team_wicket', 'new_batter',
       'power_surge_start', 'batter_runs', 'batter_balls', 'bowler_wicket',
       'batting_partners', 'next_batter', 'striker_out'],
      dtype='str')

In [362]:
df.match_won_by.sample(7)

187852                Unknown
42679           Pune Warriors
249291    Sunrisers Hyderabad
41589     Chennai Super Kings
46035         Deccan Chargers
7106      Chennai Super Kings
135968    Sunrisers Hyderabad
Name: match_won_by, dtype: str

In [363]:
# Filter only innings 1, group by match_id, take batting_team
team1 = df[df['innings'] == 1].groupby('match_id')['batting_team'].first()
team2 = df[df['innings'] == 2].groupby('match_id')['batting_team'].first()

In [364]:
df.head()

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,...,team_balls,team_wicket,new_batter,power_surge_start,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,141607,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,...,1,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,141608,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,...,2,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,141609,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,2,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,141610,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,3,0,NaN,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,141611,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,...,4,0,NaN,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

In [365]:
# match_id, date, venue, city, season, batting_team, bowling_team, toss_winner, toss_decision, match_won_by
# 'Unnamed: 0', 'match_id', 'date', 'match_type', 'event_name', 'innings',
#        'batting_team', 'bowling_team', 'over', 'ball', 'ball_no', 'batter',
#        'bat_pos', 'runs_batter', 'balls_faced', 'bowler', 'valid_ball',
#        'runs_extras', 'runs_total', 'runs_bowler', 'runs_not_boundary',
#        'extra_type', 'non_striker', 'non_striker_pos', 'wicket_kind',
#        'player_out', 'fielders', 'runs_target', 'review_batter',
#        'team_reviewed', 'review_decision', 'umpire', 'umpires_call',
#        'player_of_match', 'match_won_by', 'win_outcome', 'toss_winner',
#        'toss_decision', 'venue', 'city', 'day', 'month', 'year', 'season',
#        'gender', 'team_type', 'superover_winner', 'result_type', 'method',
#        'balls_per_over', 'overs', 'event_match_no', 'stage', 'match_number',
#        'team_runs', 'team_balls', 'team_wicket', 'new_batter',
#        'power_surge_start', 'batter_runs', 'batter_balls', 'bowler_wicket',
#        'batting_partners', 'next_batter', 'striker_out'

In [366]:
# df = df.drop(columns=['Unnamed: 0', 'match_type', 'event_name', 'innings', 'over', 'ball', 'ball_no', 'batter','bat_pos', 'runs_batter', 'balls_faced', 'bowler', 'valid_ball','runs_extras', 'runs_total', 'runs_bowler', 'runs_not_boundary','extra_type', 'non_striker', 'non_striker_pos', 'wicket_kind','player_out', 'fielders', 'runs_target', 'review_batter','team_reviewed', 'review_decision', 'umpire', 'umpires_call','player_of_match', 'win_outcome', 'day', 'month', 'year','gender', 'team_type', 'superover_winner', 'result_type', 'method','balls_per_over', 'overs', 'event_match_no', 'stage', 'match_number','team_runs', 'team_balls', 'team_wicket', 'new_batter','power_surge_start', 'batter_runs', 'batter_balls', 'bowler_wicket','batting_partners', 'next_batter', 'striker_out'])
cols_to_keep = ['match_id', 'date', 'venue', 'city', 'season', 'batting_team', 'bowling_team', 'toss_winner', 'toss_decision', 'match_won_by']
df = df[cols_to_keep]

In [367]:
grouped_df = df.groupby('match_id').first()

In [368]:
grouped_df.sample()

,date,venue,city,season,batting_team,bowling_team,toss_winner,toss_decision,match_won_by
match_id,,,,,,,,,
980989,2016-05-14,Eden Gardens,Kolkata,2016,Rising Pune Supergiants,Kolkata Knight Riders,Rising Pune Supergiants,bat,Kolkata Knight Riders

In [369]:
grouped_df.shape

(1193, 9)

In [370]:
print(grouped_df.columns.tolist())
print(grouped_df.isnull().sum())

['date', 'venue', 'city', 'season', 'batting_team', 'bowling_team', 'toss_winner', 'toss_decision', 'match_won_by']
date             0
venue            0
city             0
season           0
batting_team     0
bowling_team     0
toss_winner      0
toss_decision    0
match_won_by     0
dtype: int64

In [371]:
grouped_df.dtypes

date                str
venue               str
city                str
season           object
batting_team        str
bowling_team        str
toss_winner         str
toss_decision       str
match_won_by        str
dtype: object

In [372]:
print(team1.head())
print(team2.head())
print(type(team1))

match_id
335982    Kolkata Knight Riders
335983      Chennai Super Kings
335984         Rajasthan Royals
335985           Mumbai Indians
335986          Deccan Chargers
Name: batting_team, dtype: str
match_id
335982    Royal Challengers Bangalore
335983                Kings XI Punjab
335984               Delhi Daredevils
335985    Royal Challengers Bangalore
335986          Kolkata Knight Riders
Name: batting_team, dtype: str
<class 'pandas.Series'>

In [373]:
grouped_df['team1'] = team1
grouped_df['team2'] = team2

In [374]:
grouped_df.shape

(1193, 11)

In [375]:
grouped_df.sample()

,date,venue,city,season,batting_team,bowling_team,toss_winner,toss_decision,match_won_by,team1,team2
match_id,,,,,,,,,,,
501258,2011-05-15,Holkar Cricket Stadium,Indore,2011,Rajasthan Royals,Kochi Tuskers Kerala,Kochi Tuskers Kerala,field,Kochi Tuskers Kerala,Rajasthan Royals,Kochi Tuskers Kerala

In [376]:
grouped_df['match_won_by'].value_counts()

match_won_by
Mumbai Indians                 152
Chennai Super Kings            144
Kolkata Knight Riders          135
Rajasthan Royals               118
Royal Challengers Bangalore    114
Sunrisers Hyderabad             95
Kings XI Punjab                 85
Delhi Daredevils                67
Delhi Capitals                  53
Gujarat Titans                  39
Punjab Kings                    38
Lucknow Super Giants            32
Deccan Chargers                 29
Unknown                         24
Royal Challengers Bengaluru     22
Gujarat Lions                   13
Pune Warriors                   12
Rising Pune Supergiant          10
Kochi Tuskers Kerala             6
Rising Pune Supergiants          5
Name: count, dtype: int64

In [377]:
grouped_df['match_won_by'] = grouped_df['match_won_by'].replace({'Royal Challengers Bengaluru':'Royal Challengers Bangalore' , 'Rising Pune Supergiants':'Rising Pune Supergiant' , 'Pune Warriors':'Rising Pune Supergiant' , 'Gujarat Lions':'Gujarat Titans' , 'Punjab Kings':'Kings XI Punjab' , 'Delhi Daredevils':'Delhi Capitals' })

In [378]:
grouped_df['match_won_by'].value_counts()

match_won_by
Mumbai Indians                 152
Chennai Super Kings            144
Royal Challengers Bangalore    136
Kolkata Knight Riders          135
Kings XI Punjab                123
Delhi Capitals                 120
Rajasthan Royals               118
Sunrisers Hyderabad             95
Gujarat Titans                  52
Lucknow Super Giants            32
Deccan Chargers                 29
Rising Pune Supergiant          27
Unknown                         24
Kochi Tuskers Kerala             6
Name: count, dtype: int64

In [379]:
grouped_df = grouped_df[grouped_df['match_won_by'] !='Unknown']

In [380]:
grouped_df['match_won_by'].value_counts()

match_won_by
Mumbai Indians                 152
Chennai Super Kings            144
Royal Challengers Bangalore    136
Kolkata Knight Riders          135
Kings XI Punjab                123
Delhi Capitals                 120
Rajasthan Royals               118
Sunrisers Hyderabad             95
Gujarat Titans                  52
Lucknow Super Giants            32
Deccan Chargers                 29
Rising Pune Supergiant          27
Kochi Tuskers Kerala             6
Name: count, dtype: int64

In [381]:
print(grouped_df.shape)
print(grouped_df['match_won_by'].value_counts())

(1169, 11)
match_won_by
Mumbai Indians                 152
Chennai Super Kings            144
Royal Challengers Bangalore    136
Kolkata Knight Riders          135
Kings XI Punjab                123
Delhi Capitals                 120
Rajasthan Royals               118
Sunrisers Hyderabad             95
Gujarat Titans                  52
Lucknow Super Giants            32
Deccan Chargers                 29
Rising Pune Supergiant          27
Kochi Tuskers Kerala             6
Name: count, dtype: int64

In [382]:
print(grouped_df['team1'].value_counts())

team1
Mumbai Indians                 143
Chennai Super Kings            140
Kolkata Knight Riders          126
Royal Challengers Bangalore    117
Sunrisers Hyderabad            107
Rajasthan Royals               106
Kings XI Punjab                 96
Delhi Daredevils                69
Deccan Chargers                 43
Delhi Capitals                  43
Punjab Kings                    40
Lucknow Super Giants            35
Gujarat Titans                  29
Pune Warriors                   20
Royal Challengers Bengaluru     20
Gujarat Lions                   13
Rising Pune Supergiant           8
Kochi Tuskers Kerala             7
Rising Pune Supergiants          7
Name: count, dtype: int64

In [383]:
team_name_mapping = {
    'Royal Challengers Bengaluru': 'Royal Challengers Bangalore',
    'Punjab Kings': 'Kings XI Punjab',
    'Rising Pune Supergiants': 'Rising Pune Supergiant',
    'Delhi Daredevils': 'Delhi Capitals',
}

# Now apply to all columns
for col in ['batting_team', 'bowling_team', 'team1', 'team2', 'match_won_by', 'toss_winner']:
    grouped_df[col] = grouped_df[col].replace(team_name_mapping)

In [384]:
grouped_df = grouped_df.drop(columns=['date', 'batting_team', 'bowling_team','city'])

In [385]:
print(grouped_df.columns.to_list())
print(grouped_df.shape)

['venue', 'season', 'toss_winner', 'toss_decision', 'match_won_by', 'team1', 'team2']
(1169, 7)

In [386]:
grouped_df.dtypes

venue               str
season           object
toss_winner         str
toss_decision       str
match_won_by        str
team1               str
team2               str
dtype: object

In [387]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

cols_to_encode = ['venue','toss_winner', 'toss_decision', 'team1', 'team2', 'match_won_by']

In [388]:
label_encoders = {}

for col in cols_to_encode:
    le = LabelEncoder()
    grouped_df[col] = le.fit_transform(grouped_df[col])
    label_encoders[col] = le

In [389]:
grouped_df.sample()

          venue season  toss_winner  toss_decision  match_won_by  team1  team2
match_id
1527691      28   2026            2              1             0      0      2

In [390]:
# grouped_df = grouped_df['season'].str[:4].astype(int)
grouped_df.isna().sum()

venue            0
season           0
toss_winner      0
toss_decision    0
match_won_by     0
team1            0
team2            0
dtype: int64

In [391]:
grouped_df['season'].isna().sum()

np.int64(0)

In [392]:
grouped_df['season'] = grouped_df['season'].astype(str).str[:4].astype(int)

In [393]:
grouped_df.sample(5)

,venue,season,toss_winner,toss_decision,match_won_by,team1,team2
match_id,,,,,,,
980987,23,2016,3,1,11,13,3
419165,9,2009,0,0,0,0,9
1359491,28,2023,0,1,9,11,0
392204,22,2009,13,0,11,13,5
733987,2,2014,0,1,4,5,0

In [394]:
grouped_df.sample()

,venue,season,toss_winner,toss_decision,match_won_by,team1,team2
match_id,,,,,,,
1216498,13,2020,14,1,4,5,14

In [395]:
print(grouped_df.shape)
print(grouped_df.dtypes)
print(grouped_df.isnull().sum())
print(grouped_df.head(3))

(1169, 7)
venue            int64
season           int64
toss_winner      int64
toss_decision    int64
match_won_by     int64
team1            int64
team2            int64
dtype: object
venue            0
season           0
toss_winner      0
toss_decision    0
match_won_by     0
team1            0
team2            0
dtype: int64
          venue  season  toss_winner  toss_decision  match_won_by  team1  \
match_id
335982       23    2007           13              1             6      7
335983       41    2007            0              0             0      0
335984       16    2007           11              0             2     11

          team2
match_id
335982       13
335983        5
335984        2

In [396]:
from sklearn.model_selection import train_test_split

X = grouped_df.drop(columns=['match_won_by'])
y = grouped_df['match_won_by']

X_train, X_test, y_train, y_test = train_test_split(X,y,train_size=0.8,random_state=42)

In [397]:
# from sklearn.linear_model import LogisticRegression

# model = LogisticRegression()

In [398]:
# model.fit(X_train,y_train)

In [399]:
# y_pred = model.predict(X_test)

In [400]:
from sklearn.metrics import accuracy_score, classification_report

# print(accuracy_score(y_test, y_pred))
# print(classification_report(y_test, y_pred))

In [401]:
# random forest

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()

In [402]:
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)

In [403]:
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.4829059829059829
              precision    recall  f1-score   support

           0       0.54      0.61      0.58        31
           1       0.60      0.43      0.50         7
           2       0.44      0.27      0.33        30
           3       0.83      0.77      0.80        13
           4       0.21      0.18      0.20        22
           5       0.00      0.00      0.00         0
           6       0.46      0.63      0.53        27
           7       0.33      0.20      0.25         5
           8       0.48      0.46      0.47        28
           9       0.52      0.57      0.54        23
          10       1.00      0.33      0.50         3
          11       0.33      0.33      0.33        24
          12       0.59      0.76      0.67        21

    accuracy                           0.48       234
   macro avg       0.49      0.43      0.44       234
weighted avg       0.48      0.48      0.47       234

d:\Projects\Machine Learning\IPL_2026_Score_Prediction\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
d:\Projects\Machine Learning\IPL_2026_Score_Prediction\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
d:\Projects\Machine Learning\IPL_2026_Score_Prediction\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [404]:
# from xgboost import XGBClassifier

# xgb = XGBClassifier()

In [405]:
# xgb.fit(X_train,y_train)
# y_pred = xgb.predict(X_test)

In [406]:
# print(accuracy_score(y_test, y_pred))
# print(classification_report(y_test, y_pred))

In [408]:
import pickle

# save model
with open('../model/rf_model.pkl', 'wb') as f:
    pickle.dump(rf, f)

# save encoders
with open('../model/label_encoders.pkl', 'wb') as f:
    pickle.dump(label_encoders, f)