In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
results = pd.read_csv("../data/results.csv")
status = pd.read_csv("../data/status.csv")
sprint_results = pd.read_csv("../data/sprint_results.csv")
seasons = pd.read_csv("../data/seasons.csv")
races = pd.read_csv("../data/races.csv")
qualifying = pd.read_csv("../data/qualifying.csv")
pit_stops = pd.read_csv("../data/pit_stops.csv")
lap_times = pd.read_csv("../data/lap_times.csv")
drivers = pd.read_csv("../data/drivers.csv")
driver_standings = pd.read_csv("../data/driver_standings.csv")
constructors = pd.read_csv("../data/constructors.csv")
constructor_standings = pd.read_csv("../data/constructor_standings.csv")
constructor_results = pd.read_csv("../data/constructor_results.csv")
circuits = pd.read_csv("../data/circuits.csv")

In [3]:
results.sample(5)
# status.sample()
# sprint_results.sample()
# seasons.sample()
# races.sample()
# qualifying.sample()
# pit_stops.sample()
# lap_times.sample()
# drivers.sample()
# driver_standings.sample()
# constructor_standings.sample()
# constructor_results.sample()
# circuits.sample()

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
538,539,43,16,12,20,21,17,17,17,0.0,68,\N,\N,27,18,1:18.091,203.347,12
3829,3830,198,73,25,20,18,\N,R,22,0.0,16,\N,\N,\N,\N,\N,\N,9
10978,10979,463,152,53,36,13,13,13,13,0.0,68,\N,\N,\N,\N,\N,\N,20
17711,17712,732,356,172,26,4,\N,R,15,0.0,11,\N,\N,\N,\N,\N,\N,22
154,155,25,12,4,6,9,7,7,7,2.0,70,+41.033,5551278,24,10,1:17.758,204.218,1

In [9]:
results.shape

(26759, 18)

In [5]:
results.replace('\\N',np.nan)

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26754,26760,1144,825,210,20,14,16,16,16,0.0,57,NaN,NaN,57,1,1:25.637,222.002,11
26755,26761,1144,859,215,30,12,17,17,17,0.0,55,NaN,NaN,52,12,1:28.751,214.212,5
26756,26762,1144,822,15,77,9,NaN,R,18,0.0,30,NaN,NaN,14,19,1:29.482,212.462,130
26757,26763,1144,861,3,43,20,NaN,R,19,0.0,26,NaN,NaN,5,17,1:29.411,212.631,5
26758,26764,1144,815,9,11,10,NaN,R,20,0.0,0,NaN,NaN,NaN,0,NaN,NaN,4

In [6]:
master_df = pd.merge(results, drivers, how='left', on='driverId')

In [10]:
master_df.shape

(26759, 26)

In [11]:
master_df = pd.merge(master_df,constructors,how='left',on='constructorId')

In [12]:
master_df = pd.merge(master_df,races,how='left',on='raceId')

In [14]:
master_df = pd.merge(master_df,status,how='left',on='statusId')

In [17]:
master_df.shape

(26759, 48)

In [70]:
master_df.sample(7)

,resultId,raceId,driverId,constructorId,driver_number,grid,position,positionText,positionOrder,points,...,nationality_y,url_y,year,round,circuitId,name_y,date,time_y,url,status
15788,15789,639,224,180,2,5,2,2,2,6.0,...,British,http://en.wikipedia.org/wiki/Team_Lotus,1971,8,70,Austrian Grand Prix,1971-08-15,NaN,http://en.wikipedia.org/wiki/1971_Austrian_Gra...,Finished
23456,23461,973,817,9,3,6,3,3,3,15.0,...,Austrian,http://en.wikipedia.org/wiki/Red_Bull_Racing,2017,5,4,Spanish Grand Prix,2017-05-14,12:00:00,http://en.wikipedia.org/wiki/2017_Spanish_Gran...,Finished
4377,4378,223,23,17,11,16,NaN,R,20,0.0,...,Irish,http://en.wikipedia.org/wiki/Jordan_Grand_Prix,1997,17,26,European Grand Prix,1997-10-26,NaN,http://en.wikipedia.org/wiki/1997_European_Gra...,Water leak
16623,16624,679,346,167,12,16,NaN,R,12,0.0,...,British,http://en.wikipedia.org/wiki/Cooper_Car_Company,1967,1,30,South African Grand Prix,1967-01-02,NaN,http://en.wikipedia.org/wiki/1967_South_Africa...,Engine
22373,22377,911,20,9,1,3,5,5,5,10.0,...,Austrian,http://en.wikipedia.org/wiki/Red_Bull_Racing,2014,12,13,Belgian Grand Prix,2014-08-24,12:00:00,http://en.wikipedia.org/wiki/2014_Belgian_Gran...,Finished
8646,8647,376,133,35,36,0,NaN,F,31,0.0,...,Italian,http://en.wikipedia.org/wiki/Dallara,1988,5,7,Canadian Grand Prix,1988-06-12,NaN,http://en.wikipedia.org/wiki/1988_Canadian_Gra...,Did not prequalify
24752,24758,1037,20,6,5,14,13,13,13,0.0,...,Italian,http://en.wikipedia.org/wiki/Scuderia_Ferrari,2020,7,13,Belgian Grand Prix,2020-08-30,13:10:00,http://en.wikipedia.org/wiki/2020_Belgian_Gran...,Finished

In [19]:
master_df = master_df.replace('\\N',np.nan)

In [42]:
data_to_drop = master_df.isnull().sum().sort_values(ascending=False)

In [38]:
master_df.isin(['\\N']).sum().sum()

np.int64(0)

In [63]:
col = data_to_drop[data_to_drop > 11000]

In [64]:
ghost_columns = [
    'sprint_time', 'sprint_date', 'quali_time', 'quali_date', 
    'fp3_time', 'fp3_date', 'fp2_time', 'fp2_date', 
    'fp1_time', 'fp1_date', 'number_y', 'time_x'
]

In [68]:
master_df = master_df.drop(columns=ghost_columns, errors='ignore')

In [66]:
master_df = master_df.rename(columns={
    'number_x': 'driver_number',
    'nationality_x': 'driver_nationality',
    'url_x': 'driver_url' # (Add any other _x columns you see here)
})

In [67]:
master_df = master_df.replace(r'\\N', np.nan, regex=True)

In [69]:
print("New Shape:", master_df.shape)
print("\nTop 10 Missing Values Now:")
print(master_df.isnull().sum().sort_values(ascending=False).head(10))

New Shape: (26758, 36)

Top 10 Missing Values Now:
milliseconds       19079
fastestLap         18507
fastestLapSpeed    18507
fastestLapTime     18507
time_y             18469
rank               18249
code               16581
position           10953
driver_number          6
driverId               0
dtype: int64

In [72]:
master_df.to_csv("Master_data")